### ISSUE TITLE
Update menu in header

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/sparkplug.eclipse.org#112]
There are some navigation issues on the site. As a simple solution, we would like to update the menu in the header. Here is the menu structure: https://docs.google.com/document/d/1MxFKCDitzssneojAaHi1cAqn-UV6B0I1ouJuE9dF76k/edit?usp=sharing. The "Compatibility" section is still in the works, so we can add it later (depending on when this can be implemented).

CC @hassanjaber98

**Comment by linkfang** [comment]
Hi @shanda-eclipse ,

1 question.
For the new page for join us form, what URL would you like to use?

We already have a "/join-us" for "Join Us" button, so this is not available.

And if we use "/membership/join-us/", then the page will have a menu level tree like this "Eclipse Sparkplug Working Group  / Membership  / Join Us"
![image](https://user-images.githubusercontent.com/43075439/143610475-4d715ce9-684f-42e6-9382-94ad71851c82.png)

When user clicks on the membership, they will see nothing because we don't have a /membership page. 
![image](https://user-images.githubusercontent.com/43075439/143610607-273c294a-a50d-4bd5-afe5-26dcd89a756e.png)

I am thinking using "/become-a-member". This aligns the option "Become a Member", though it doesn't feel very consistent to other join-us embedded forms. (which are either /join-us or /membership/join-us)

WDYT?

**Comment by shanda-eclipse** [comment]
What about "/contact-join-us"? This way we aren't adding a level but if anyone is searching for join-us pages this would (theoretically) come up.

**Comment by linkfang** [comment]
sounds good!

**Comment by linkfang** [comment]
Please preview the changes here:
https://deploy-preview-113--eclipsefdn-sparkplug.netlify.app/

new contact form page:
https://deploy-preview-113--eclipsefdn-sparkplug.netlify.app/contact-join-us/

As the embed form change is related to this one, so I include that in this preview.
Now only the "Become a Member" sub-menu will take users to the new contact form and all other "Join us" link/option will take user to the existing /join-us page.

**Comment by shanda-eclipse** [comment]
+1 for embedded form

For the menu, can we adjust the order of the menu items? Rather than alphabetical, I would like them in this order:

About
- Sparkplug Specification
- FAQ
- Mailing List
- Slack Channel

Membership
- Value of Membership (I had the wrong link in the doc, this should link to https://f.hubspotusercontent10.net/hubfs/5413615/sparkplug-member-prospectus%202020.pdf)
- Our Members
- Become a Member

**Comment by linkfang** [comment]
Sure, here is the new order:
https://deploy-preview-113--eclipsefdn-sparkplug.netlify.app/

**Comment by shanda-eclipse** [comment]
Sorry, I also had the wrong link for the slack workspace: https://join.slack.com/t/eclipse-sparkplug-wg/shared_invite/zt-btcn48au-luMXPXMbMhBzS4pCaLO6_w

**Comment by linkfang** [comment]
No worries, Friday's fault

Here is it:
https://deploy-preview-113--eclipsefdn-sparkplug.netlify.app/

**Comment by shanda-eclipse** [comment]
+1 from me. @hassanjaber98 can you also review and approve?

**Comment by ericpoirier** [comment]
@hassanjaber98 any objections if we move forward with these changes?

Thanks.

**Comment by hassanjaber98** [comment]
+1 @ericpoirier
